### ISSUE TITLE
`links` option in `npm_install` does not link typescript declaration files

### ISSUE THREAD

**Issue by riyavsinha** [bazelbuild/rules_nodejs#2961]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `npm_install`

### Is this a regression?

Not sure

### Description

After building a local `local_pkg` in a monorepo, I want `pkg_a` to be able to depend on it using the `links` option in `npm_install`. `local_pkg` outputs types when it builds on its own, but the types are not copied into the `external` directory for `pkg_a`, and `pkg_a` therefore is not able to build

## 🔬 Minimal Reproduction

https://github.com/riyavsinha/bazel_npm_install_links

Run:
```
npx bazel build //packages/pkg_a/server/src:server
```

## 🔥 Exception or Error

```
packages/pkg_a/server/src/run-generator.ts(1,29): error TS2307: Cannot find module '@local_pkg/random-generators' or its corresponding type declarations.
```

Looking at `bazel-bin/packages/local_pkg/src`, the type definitions are there. However, in `bazel-bin/external/pkg_a_npm/@example-org/local-pkg/` the type definitions are not copied over, and `pkg_a` therefore is not able to find the type declarations I believe.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
      macOS 11.5.2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
    Bazelisk version: v1.10.1
    Build label: 4.2.1
    Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Mon Aug 30 15:24:28 2021 (1630337068)
    Build timestamp: 1630337068
    Build timestamp as int: 1630337068
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
     4.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by riyavsinha** [comment]
I do see that `npm_install` is just calling `npm_link` from `linker`, so maybe its actually a problem there, but I think thats as far as I'm able to deduce

**Comment by alexeagle** [comment]
thanks for the repro.

you can check what inputs Bazel is passing to that `tsc` compile action created by `ts_project` - we want to see if the .d.ts typings are making it across:

```
bazel aquery //packages/pkg_a/server/src:server | grep Inputs | tr ',' '\n' | grep local_pkg/src

 bazel-out/k8-fastbuild/bin/packages/local_pkg/src/random-generators.d.ts
 bazel-out/k8-fastbuild/bin/packages/local_pkg/src/random-generators.d.ts.map
 ```
 
 this shows that the problem is with your typescript config - you need to use the `paths` property to tell tsc where to resolve `@local_pkg` imports
 
 ```
 "paths": {
      "@local_pkg/*": ["../../../bazel-out/k8-fastbuild/bin/packages/local_pkg/src/*"],
    },
```
