### ISSUE TITLE
[karma-server]: UncaughtException:: file.detectType is not a function

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_nodejs#2093]
Please see the Karma project's https://github.com/karma-runner/karma/issues/3537#, where they say the issue is with rules_nodejs.

**Comment by applmak** [comment]
Confirmed: karma ^5.1.0 breaks the implementation of concatjs. The right fix to to convert `bundledFile` ([here](https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/karma/index.ts#L32)) to a File. I suspect this could be done by importing {File} from `@types/karma`, if it's exposed.

**Comment by mattem** [comment]
This is likely still an issue, reopening

**Comment by sgammon** [comment]
just ran into this. still an issue

**Comment by sgammon** [comment]
FYI i was able to work around this with the following pinned versions in `package.json`, which roughly match the `rules_nodejs` deps:
```json
    "karma": "~4.1.0",
    "karma-coverage": "^2.0.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-firefox-launcher": "^2.1.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "^1.5.2",
    "karma-requirejs": "1.1.0",
    "karma-safari-launcher": "^1.0.0",
    "karma-sourcemap-loader": "0.3.7",
```

**Comment by flolu** [comment]
I am encountering the same issue. In my case it was enough to change the version of `karma` to

```
"karma": "~4.4.1"
```

The error occurs after upgrading `karma` to v5

**Comment by mattsoulanille** [comment]
I'm still having this issue. Posting this so the bot doesn't close it. Currently working with `karma: 5.0.6` but breaks with 6.3.2.
