### ISSUE TITLE
Cannot find npm modules installed in a shared repository when compiling typescript

### ISSUE THREAD

**Issue by ericsong** [bazelbuild/rules_nodejs#3377]
# 🐞 bug report

### Affected Rule

Not 100% sure but either `ts_project`, `yarn_install`, or some interaction between the two.

### Is this a regression?

Yes. I have a working example with 4.6.2 which does not work in 5.3.0

### Description

Example: https://github.com/ericsong/rules_nodejs/tree/stable/examples/monorepo-5.3.0

When compiling typescript, cannot import NPM packages installed in a "shared third_party" bazel repository like one might see in a monorepo configuration.

Folder setup:
```
\
  \third_party # contains a list of third party npm packages
  \ui # contains an application that needs to import an npm package declared in `third_party`
  WORKSPACE
```

The exact same setup works with rules_nodejs version 4.6.2 as seen here, https://github.com/ericsong/rules_nodejs/tree/stable/examples/monorepo-4.6.2. 

## 🔬 Minimal Reproduction

https://github.com/ericsong/rules_nodejs/tree/stable/examples/monorepo-5.3.0

## 🔥 Exception or Error
```
INFO: Invocation ID: 437fc0ea-e77c-45ea-8163-1c7dac53511e
DEBUG: /data/home/eric/.cache/bazel/_bazel_eric/39f14e9dac564798c1d9f3f2910b9f71/external/build_bazel_rules_nodejs/index.bzl:65:14: node_repository attribute not set and no repository named 'nodejs_toolchains' exists; installing default node
DEBUG: /data/home/eric/.cache/bazel/_bazel_eric/39f14e9dac564798c1d9f3f2910b9f71/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
INFO: Analyzed target //ui:bundle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /data/home/eric/code/rules_nodejs/examples/monorepo-5.3.0/ui/BUILD.bazel:16:11: Compiling TypeScript project //ui:ts [tsc -p ui/tsconfig.json] failed: (Exit 2): tsc.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/typescript/bin/tsc.sh --project ui/tsconfig.json --outDir bazel-out/k8-fastbuild/bin/ui --rootDir ui ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ui/index.tsx(1,24): error TS2307: Cannot find module 'react'.
ui/index.tsx(2,27): error TS2307: Cannot find module 'react-dom'.
Target //ui:bundle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.864s, Critical Path: 3.17s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Ubuntu 18.04.2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 5.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 24 14:02:30 2022 (1648130550)
Build timestamp: 1648130550
Build timestamp as int: 1648130550
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
5.3.0
  </code>
</pre>

**Anything else relevant?**

I'm a bit new to Bazel so it's possible that I configured something incorrectly. Open to suggestions for a more ideal monorepo setup where multiple projects can share the same dependencies declared through a single bazel repo.
