### PR TITLE
feat(create): add workers flags

### PR DESCRIPTION
**Pull request by alexeagle**
This should help users stay on the happy path

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by gregmagolan** [comment]
Same failures I saw in https://github.com/bazelbuild/rules_nodejs/pull/861. Likely related to worker mode in 0.27.0rc5 then.

**Comment by alexeagle** [comment]
It's https://github.com/bazelbuild/rules_typescript/issues/449 - not related to recent Bazel I think

File: e2e/ts_library/reference_types_directive/BUILD.bazel [hunk 1]
```diff
@@ -7,7 +7,7 @@ ts_library(
     expected_diagnostics = [
         "TS2304: Cannot find name 'Hammer'",
     ],
-    node_modules = "@npm//:node_modules",
+    node_modules = "@npm//:node_modules_filegroup",
```
Comment (alexeagle) [inline e2e/ts_library/reference_types_directive/BUILD.bazel]: this makes me think it's a breaking change. I hoped we could keep the old code building?

File: e2e/ts_library/reference_types_directive/tsconfig_types.ts [hunk 2]
```diff
@@ -1,3 +1,4 @@
+describe('@jasmine/types types are included via tsconfig.json "types"=["jasmine"]', () => {});
```
Comment (alexeagle) [inline e2e/ts_library/reference_types_directive/tsconfig_types.ts]: should this be empty? just a stray addition?

File: e2e/ts_library/reference_types_directive/BUILD.bazel (hunk 1 above)
Comment (gregmagolan) [reply e2e/ts_library/reference_types_directive/BUILD.bazel]: Because `@npm//:node_modules` is not a node_modules_library and no longer a filegroup and the rules_typescript change makes ts_library now all of its .d.ts files and stamp out the `types` in tsconfig this ts_library now successfully compiles. This test was checking for the missing dep "TS2304: Cannot find name 'Hammer'" so for the test to work as designed the node_modules must be a plain filegroup.

File: e2e/ts_library/reference_types_directive/tsconfig_types.ts (hunk 2 above)
Comment (gregmagolan) [reply e2e/ts_library/reference_types_directive/tsconfig_types.ts]: Just testing that `describe` is a valid symbol. I'll clean it up.

File: e2e/ts_library/WORKSPACE [hunk 3]
```diff
@@ -26,6 +26,14 @@ load("@build_bazel_rules_nodejs//:defs.bzl", "yarn_install")
 
 yarn_install(
     name = "npm",
+    manual_build_file_contents = """
+filegroup(
+  name = "node_modules_filegroup",
```
Comment (alexeagle) [inline e2e/ts_library/WORKSPACE]: add a comment here that this is to exclude hammerjs because the test asserts that it's missing?
