### ISSUE TITLE
Invoking npm within a nodejs_binary is likely to fail in some cases.

### ISSUE THREAD

**Issue by thesayyn** [bazelbuild/rules_nodejs#2197]
# 🐞 bug report

### Affected Rule

nodejs_binary

### Is this a regression?
Not sure but it was working fine in 1.7.0.  
Probably because there was no version skew between local npm and vendored node.

### Description

Invoking npm within a nodejs_binary fails with an unclear error.

## 🔬 Minimal Reproduction

1- Create a workspace via @bazel/create and create a nodejs_binary target and write a script that invokes npm

## 🔥 Exception or Error

npm install has failed. code: 1
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/local/bin/npm
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /usr/local/bin/npm:19:21
    at Object.<anonymous> (/usr/local/bin/npm:155:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/bin/npm' ]
}

## 🌍  Your Environment

**Operating System:**

uname: Darwin 10.15.6

**Output of `bazel version`:**

Bazelisk version: v1.6.1
Build label: 3.5.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:16:21 2020 (1599077781)
Build timestamp: 1599077781
Build timestamp as int: 1599077781

**Rules_nodejs version:**
2.1.0 

**Anything else relevant?**

I think the local npm does not support the vendored node's version thus leading to this error. I think npm should be vendored as well and should be present in the PATH.

**Comment by thesayyn** [comment]
Most likely this is an interoperability issue between vendored node and npm in local system.  The issue can be reproduced by using the which package in npm. When i run `which.sync("npm")` it sees the local npm in the system (`/usr/local/bin/npm`).

**Comment by thesayyn** [comment]
I think this is still relevant.
