### ISSUE TITLE
Jest Tests Stop Working After Upgrading to 1.6.0

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#1848]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: i don't know

### Is this a regression?

It worked with version 1.5.0

## 🔬 Minimal Reproduction
https://github.com/flolu/jest-rules-nodejs-issue

## 🔥 Exception or Error
```
FAIL ./test.spec.js
  ● Test suite failed to run

    Cannot find module 'jest_rules_nodejs_issue/num' from 'test.spec.js'

      at Resolver.resolveModule (../../../../../node_modules/jest-resolve/build/index.js:299:11)
      at ../../../test.spec.ts:1:1
      at test.spec.js:3:13
      at Object.<anonymous> (test.spec.js:8:3)
```

## 🌍  Your Environment

**Operating System:** Ubuntu 20.04

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.4.0
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
  </code>
</pre>

**Rules_nodejs version:** 1.6.0

**Comment by alexeagle** [comment]
Looks like duplicate of #1823
