### ISSUE TITLE
Cannot find module from external repository after upgrading do 5.0.1

### ISSUE THREAD

**Issue by adworzynski** [bazelbuild/rules_nodejs#3291]
# 🐞 bug report

### Affected Rule

ts_project

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 4.6.1

### Description

 After upgrading form version 4.6.1 to 5.0.1 the project no longer compiles.

## 🔬 Minimal Reproduction
# Workspace configuration
<pre><code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "f690430f4d4cc403b5c90d0f0b21842183b56b732fff96cfe6555fe73189906a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.0.1/rules_nodejs-5.0.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "npm_commitlint",
    package_json = "//tools/bazel/commitlint:package.json",
    yarn_lock = "//tools/bazel/commitlint:yarn.lock",
)

yarn_install(
    name = "npm_lint",
    package_json = "//tools/bazel/lint:package.json",
    yarn_lock = "//tools/bazel/lint:yarn.lock",
)

yarn_install(
    name = "npm",
    package_json = "//tools/bazel/nodejs:package.json",
    yarn_lock = "//tools/bazel/nodejs:yarn.lock",
)
</code></pre>

# Build file
<pre><code>
ts_project(
    name = "project",
    tsconfig = ":tsconfig",
    deps = ["@npm//fp-ts"],
    srcs = glob(["src/*.ts"]),
    declaration = True,
)

</code></pre>

## 🔥 Exception or Error

<pre><code>
ERROR: /home/dworek/projects/myproject/packages/project/BUILD:8:11: Compiling TypeScript project //packages/project:project [tsc -p packages/project/tsconfig.build.json] failed: (Exit 2): tsc.sh failed: error executing command 
  (cd /home/dworek/.cache/bazel/_bazel_dworek/1ce0ed8fd43335e711405d5a1704d0f4/sandbox/linux-sandbox/63/execroot/myproject && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS=tools/bazel/nodejs \
    COMPILATION_MODE=fastbuild \
  bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/typescript/bin/tsc.sh --project packages/project/tsconfig.build.json --outDir bazel-out/k8-fastbuild/bin/packages/project --rootDir packages/project --declarationDir bazel-out/k8-fastbuild/bin/packages/project '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/packages/project/_project_TsProject.module_mappings.json')
# Configuration: 28ff57593ba01d914893f9cd455c859110ce813ccf3771961541220915f453dc
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
packages/project/src/index.ts(1,21): error TS2307: Cannot find module 'fp-ts' or its corresponding type declarations.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.11.0
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "f690430f4d4cc403b5c90d0f0b21842183b56b732fff96cfe6555fe73189906a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.0.1/rules_nodejs-5.0.1.tar.gz"],
)

"@bazel/typescript": "^5.0.1",
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
It works for me: https://github.com/alexeagle/repro_rnj_3291

Can you amend that repro so that it fails like in your case?

**Comment by adworzynski** [comment]
https://github.com/adworzynski/repro_rnj_3291

I've moved package.json to subdirectory and adjust WORKSPACE.

**Comment by alexeagle** [comment]
I see - the difference is https://docs.aspect.build/bazelbuild/rules_nodejs/5.0.0/docs/builtins.html#yarn_install-package_path

With `exports_directories_only` the node_modules tree will be linked under `tools/node/node_modules` next to the package.json file since it is nested.

You can just set `package_path = "/"` to make it linked at the repo root instead, like it was in 4.x.

**Comment by alexeagle** [comment]
I added a note on the migration wiki https://github.com/bazelbuild/rules_nodejs/wiki/Migrating-to-5.0#exports_directories_only

**Comment by adworzynski** [comment]
Thank you, works now.
