### PR TITLE
Set --preserve-symlinks-main flag

### PR DESCRIPTION
**Pull request by gregmagolan**
…along with --preserve-symlinks flag when node version is 10.2.0 or greater

This is a necessary prefactor for https://github.com/bazelbuild/rules_nodejs/pull/777.

Failure in #777 without this is in @bazel/labs package:

```
ERROR: /Users/greg/google/gregmagolan/rules_nodejs/packages/labs/webpack/test/BUILD.bazel:5:1: Bundling JavaScript bazel-out/darwin-fastbuild/bin/webpack/test/bundle.js [webpack] failed (Exit 1) cli failed: error executing command bazel-out/host/bin/external/npm_bazel_labs/webpack/cli bazel-out/darwin-fastbuild/bin/webpack/test/bundle.js-0.params

Use --sandbox_debug to see verbose messages from the sandbox
Error: @npm_bazel_labs//webpack:cli_bin cannot find module './src/cli' required by '/Users/greg/google/gregmagolan/rules_nodejs/packages/labs/webpack/index.js'
  looked in:
    built-in, relative, absolute, nested node_modules - Error: Cannot find module './src/cli'
    runfiles - Error: Cannot find module '/private/var/tmp/_bazel_greg/b0cf9547710e5f9671e4ba2447cc48b2/sandbox/darwin-sandbox/8/execroot/npm_bazel_labs/bazel-out/host/bin/external/npm_bazel_labs/webpack/cli.runfiles/src/cli'
    node_modules attribute (npm/node_modules) - Error: Cannot find module '/private/var/tmp/_bazel_greg/b0cf9547710e5f9671e4ba2447cc48b2/sandbox/darwin-sandbox/8/execroot/npm_bazel_labs/bazel-out/host/bin/external/npm_bazel_labs/webpack/cli.runfiles/npm/node_modules/src/cli'

    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_greg/b0cf9547710e5f9671e4ba2447cc48b2/execroot/npm_bazel_labs/bazel-out/host/bin/external/npm_bazel_labs/webpack/cli_bin_loader.js:458:17)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/greg/google/gregmagolan/rules_nodejs/packages/labs/webpack/index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
INFO: Elapsed time: 25.450s, Critical Path: 10.40s
INFO: 3 processes: 3 worker.
FAILED: Build did NOT complete successfully
```

This error is coming from:

```
nodejs_binary(
    name = "cli",
    data = [
        "//webpack/src:cli_lib",
        "@npm//webpack",
    ],
    entry_point = ":index.js",
    visibility = ["//visibility:public"],
)
```

where webpack cli entry point `index.js` in runfiles is resolved to the real path without `--preserve-symlinks-main`: `/Users/greg/google/gregmagolan/rules_nodejs/packages/labs/webpack/index.js` and it can't require `'./src/cli'` which is only in runfiles (as it's a ts_library output) relative to the symlink entry point.

---

Note: the real node main was the generated node loader (derived from `internal/node/node_loader.js` template) but in that loader the following code:

```
  // Set the actual entry point in the arguments list.
  // argv[0] == node, argv[1] == entry point.
  // NB: entry_point below is replaced during the build process.
  var mainScript = process.argv[1] = ENTRY_POINT;
  try {
    module.constructor._load(mainScript, this, /*isMain=*/true);
```

reset main by using `module.constructor._load` so that call requires `--preserve-symlinks-main` to be set in order for the runfiles symlink to be preserved.

---

Also note: that entry point `index.js` was added in the entry_point PR as there was no way to specify cli.js as the entry point since it is an output from the `ts_library` that compiled `cli.ts`. I'm still working on an elegant solution to that problem.

### CODE REVIEW

File: .circleci/config.yml [hunk 1]
```diff
@@ -11,7 +11,7 @@
 # If you change the `default_docker_image` version, also change the `cache_key` version
 var_1: &default_docker_image circleci/node:10.12
 var_2: &browsers_docker_image circleci/node:10.12-browsers
-var_3: &cache_key node-0.12-{{ checksum "yarn.lock" }}-{{ checksum "examples/program/yarn.lock" }}-{{ checksum "internal/npm_install/test/package/yarn.lock" }}
+var_3: &cache_key node-0.12-{{ checksum "yarn.lock" }}-{{ checksum "examples/program/yarn.lock" }}-{{ checksum "internal/npm_install/test/package/yarn.lock" }}-2
```
Comment (gregmagolan) [inline .circleci/config.yml]: cache bust needed as it was dirtied from #777 when changing the tools/npm/bazel_workspaces files
