### ISSUE TITLE
Worker throws error after 4.1.0 upgrade

### ISSUE THREAD

**Issue by matthewjh** [bazelbuild/rules_nodejs#2953]
# 🐞 bug report

### Affected area

@bazel/worker

### Is this a regression?

Yes. It worked in 4.0.0

### Description

After upgrading to 4.1.0, my ts_project workers throw an error when processing the first set of inputs:

Compilation failed:
 TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at /home/matt/.cache/bazel/_bazel_matt/e89f5bf18c40d5d717985af5d685a71b/bazel-workers/worker-1-TsProject/web/external/npm/node_modules/@bazel/worker/src/worker.js:103:53
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/home/matt/.cache/bazel/_bazel_matt/e89f5bf18c40d5d717985af5d685a71b/bazel-workers/worker-1-TsProject/web/external/npm/node_modules/@bazel/worker/src/worker.js:101:79)
    at Generator.next (<anonymous>)
    at fulfilled (/home/matt/.cache/bazel/_bazel_matt/e89f5bf18c40d5d717985af5d685a71b/bazel-workers/worker-1-TsProject/web/external/npm/node_modules/@bazel/worker/src/worker.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Commenting out this line eliminates the issue:

```python
inputs[input.path] = Buffer.from(input.digest).toString("hex");
```

https://github.com/bazelbuild/rules_nodejs/blob/4.1.0/packages/worker/src/worker.ts#L101

And indeed, logging the "input" objects shows they lack either a `path` or a `digest` property:

```json
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/fill-range"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/to-regex-range"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/glob-parent"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/is-glob"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/is-extglob"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/is-binary-path"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/binary-extensions"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/dependency-graph"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/graceful-fs"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/jsonfile"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/universalify"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/magic-string"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/sourcemap-codec"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
{"wrappers_":null,"arrayIndexOffset_":-1,"array":["external/npm/node_modules/source-map"],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}
```

## 🔬 Minimal Reproduction

None at the moment. I can not reproduce in this repo at the 4.1.0 tag, suggesting the problem is only reproducible with the @bazel/* packages that are published to npm. I assume we don't need to npm install @bazel/worker (I didn't).

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.2.1
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.1.0
  </code>
</pre>

**Anything else relevant?**

@thesayyn any idea what the problem is?

**Comment by thesayyn** [comment]
Uh oh, that's bizarre 😰  

Seems like the digest is missing from the WorkRequest inputs. 

Could you please try if you have the same issue with bazel 4.1.0? 

I suspect that there might be a change in bazel that leads to this. such as not sending the digest for the first round of work request.

**Comment by matthewjh** [comment]
Thanks!

I just tried with 4.1.0, no luck (same inputs, same error)

**Comment by thesayyn** [comment]
Oh, shoot. The digest can be undefined. 

https://github.com/bazelbuild/bazel/blob/97643ad92d86179d21b2526e9f9804045d025f21/src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnRunner.java#L238

**Comment by thesayyn** [comment]
Will send a PR to fix this asap!

**Comment by matthewjh** [comment]
Thank you!

**Comment by thesayyn** [comment]
@matthewjh  fixed in 4.2.0

**Comment by alexeagle** [comment]
fixed by  #2954

**Comment by thesayyn** [comment]
I found what caused this after a long time. https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/worker_protocol.proto uses proto3 and the default value for `bytes` type is empty uintarray8 but because of the issue https://github.com/thesayyn/protoc-gen-ts/issues/107 the default value for empty bytes field is null.
