### ISSUE TITLE
Outdated documentation links for tsetse errors

### ISSUE THREAD

**Issue by tony-scio** [bazelbuild/rules_nodejs#2367]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_library

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Presumably the links worked at some point

### Description

 After v3.0.0 upgrade, I started getting errors like:
```
error TS21231: [tsetse] type assert `JSON.parse() as SomeExplicitType` for type & optimization safety.
	See http://tsetse.info/must-type-assert-json-parse.

157   return Array.from(newFilters.entries()).map(([k, v]) => ({ ...JSON.parse(k), values: v }))
```

1. http://tsetse.info/must-type-assert-json-parse is broken. 
2. https://tsetse.info/ says it moved to https://github.com/bazelbuild/rules_nodejs/tree/3.x/third_party/github.com/bazelbuild/rules_typescript, but clicking the message goes to https://github.com/bazelbuild/rules_typescript
3. That pages says it moved to https://github.com/bazelbuild/rules_nodejs/tree/3.x/third_party/github.com/bazelbuild/rules_typescript, but clicking that gives a 404.

A google search for `TS21231` doesn't turn up anything relevant high in the results. So I'm at a dead end looking for the documentation.

## 🔬 Minimal Reproduction

Attempt to load http://tsetse.info/must-type-assert-json-parse

## 🔥 Exception or Error

<pre><code>

</code></pre>
<img width="653" alt="Screen Shot 2020-12-23 at 10 58 17 AM" src="https://user-images.githubusercontent.com/49661492/103029044-c9f37880-450d-11eb-9849-a84e8393c022.png">

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OSX
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 3.7.2-homebrew
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
The docs are in https://github.com/bazelbuild/rules_nodejs/tree/stable/third_party/github.com/bazelbuild/rules_typescript/docs
But they need to be regenerated with the latest sources, and then figure out where to host it now that we slurped in rules_typescript.

Ideally tsetse should be a standalone project.

**Comment by alexeagle** [comment]
Hmm it looks like I registered the tsetse.info domain under my alexeagle@google.com account which I no longer have. will take some research to figure out how to transfer it...

**Comment by EliSchleifer** [comment]
Maybe someone can add documentation to the rules_typescript/docs for this rule in the meantime. That folder hasn't been updated in 2 years.

**Comment by davido** [comment]
I also start seeing it after migration to 5.1.0:


```
  $ bazelisk build tools/node_tools/...
[...]
ERROR: /home/davido/projects/gerrit/tools/node_tools/polygerrit_app_preprocessor/BUILD:7:11: Compiling TypeScript (prodmode) //tools/node_tools/polygerrit_app_preprocessor:preprocessor failed: (Exit 1): tsc_wrapped.sh failed: error executing command (from target //tools/node_tools/polygerrit_app_preprocessor:preprocessor) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@bazel/concatjs/bin/tsc_wrapped.sh @@bazel-out/k8-fastbuild/bin/tools/node_tools/polygerrit_app_preprocessor/preprocessor_tsconfig.json
tools/node_tools/polygerrit_app_preprocessor/links-updater.ts:42:40 - error TS21231: [tsetse] type assert `JSON.parse() as SomeExplicitType` for type & optimization safety.
	See http://tsetse.info/must-type-assert-json-parse.

42   const jsonRedirects: JSONRedirects = JSON.parse(fs.readFileSync(process.argv[3], {encoding: "utf-8"}));
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR: /home/davido/projects/gerrit/tools/node_tools/polygerrit_app_preprocessor/BUILD:7:11: Compiling TypeScript (devmode) //tools/node_tools/polygerrit_app_preprocessor:preprocessor failed: (Exit 1): tsc_wrapped.sh failed: error executing command (from target //tools/node_tools/polygerrit_app_preprocessor:preprocessor) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@bazel/concatjs/bin/tsc_wrapped.sh @@bazel-out/k8-fastbuild/bin/tools/node_tools/polygerrit_app_preprocessor/preprocessor_es5_tsconfig.json
tools/node_tools/polygerrit_app_preprocessor/links-updater.ts:42:40 - error TS21231: [tsetse] type assert `JSON.parse() as SomeExplicitType` for type & optimization safety.
	See http://tsetse.info/must-type-assert-json-parse.

42   const jsonRedirects: JSONRedirects = JSON.parse(fs.readFileSync(process.argv[3], {encoding: "utf-8"}));
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR: /home/davido/projects/gerrit/tools/node_tools/polygerrit_app_preprocessor/BUILD:31:14 Bundling JavaScript tools/node_tools/polygerrit_app_preprocessor/links-updater-bundle.js [rollup] failed: (Exit 1): tsc_wrapped.sh failed: error executing command (from target //tools/node_tools/polygerrit_app_preprocessor:preprocessor) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@bazel/concatjs/bin/tsc_wrapped.sh @@bazel-out/k8-fastbuild/bin/tools/node_tools/polygerrit_app_preprocessor/preprocessor_es5_tsconfig.json
INFO: Elapsed time: 52.872s, Critical Path: 47.48s
INFO: 61 processes: 54 internal, 3 linux-sandbox, 4 worker.
FAILED: Build did NOT complete successfully
```

**Comment by alexeagle** [comment]
I'd love to get tsetse up and running again, but I don't know of a path to get it to work with `tsc` and the integration with `ts_library` isn't going to be maintained anymore now that `@bazel/concatjs` package is in maintenance mode. I'm not going to have time but if anyone is familiar with the TS compiler apis and wants to help, that would be great.

**Comment by tylerhou** [comment]
(I was the original author of this rule. Sorry for the missing documentation; one possible reason the documentation is missing is because Google internally removed this rule in favor of changing the return type of `JSON.parse` to `unknown`.) Since this currently the top result for `http://tsetse.info/must-type-assert-json-parse`, I felt like I might as well document the rule here.

To fix this warning, do what the warning says: add a type assertion to the result of `JSON.parse`: `JSON.parse(...) as MyType`.

One rationale is because `JSON.parse` returns `any`, and generally any should be avoided because it introduces a potential hole in the type system. You can still use any, but you have to explicitly assert it as such `JSON.parse(...) as any`. Depending on your linter settings you might have to add the normal lintignore annotations for any.

The second rationale is that Closure will happily rename accesses on `JSON.parse` if there is no declared type for the result object. That is, Closure might mangle accesses on the obj, causing runtime errors that only show up when optimization is turned on (usually in production). For example, `JSON.parse('{"hello": "world"}').hello` might be compiled to `JSON.parse('{"hello": "world"}').a` when property-renamed. The fix is to create an interface for that type via `declare interface Result { hello: string; }`. The assertion isn't necessary—once the interface is declared Closure won't rename the `hello` property—but enforcing the type assertion rule helped remind programmers to declare one.

It was difficult to detect all cases like `const obj: MyType = JSON.parse(...);`, so I didn't bother. In those cases, you should rewrite the statement as `const obj = JSON.parse(...) as MyType`.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
