### ISSUE TITLE
Updating to 0.32.2 Error: missing input digest for 

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_nodejs#885]
# 🐞 bug report

### Description

Hi, I'm trying to update [this library](https://github.com/Dig-Doug/ts-protoc-gen/tree/rules-node-update) to use v0.32.2 but I've hit an error I can't figure out.

### Affected Rule

Not sure. The project I'm updating uses lots of rules, the error message isn't clear enough to pin point which one.

### Is this a regression?

Maybe. I'm updating from `0.30.1`.

## 🔬 Minimal Reproduction

```bash
cd /tmp
git clone https://github.com/Dig-Doug/ts-protoc-gen.git 
cd ts-protoc-gen
git checkout f628f0c38c7191eb349e4979ea1971c84bb1ca6a

# I've tried this twice, one time I got a different error and ran 'yarn install', then I saw error 2 (below)

bazel --bazelrc=/dev/null build //src
# Prints error 1
```

## 🔥 Exception or Error

Error 1
<pre><code>
INFO: Analyzed target //src:src (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /tmp/ts-protoc-gen/src/BUILD.bazel:5:1: Compiling TypeScript (devmode) //src:src failed (Exit 1)
Compilation failed Error: missing input digest for ... <many-file-paths>
</code></pre>

Error 2
<pre><code>
INFO: Analyzed target //src:src (342 packages loaded, 9487 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/doug/.cache/bazel/_bazel_doug/240c47d65309926be17d6e1b95674426/sandbox
ERROR: missing input file '@npm//:node_modules/@bazel/typescript/devserver/devserver-windows_x64.exe'
ERROR: /home/doug/.cache/bazel/_bazel_doug/240c47d65309926be17d6e1b95674426/external/npm/@bazel/typescript/bin/BUILD.bazel:18:1: @npm//@bazel/typescript/bin:tsc_wrapped: missing input file '@npm//:node_modules/@bazel/typescript/devserver/devserver-windows_x64.exe'
</code></pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu 18.04.2 LTS

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.27.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:00:46 2019 (1560776446)
Build timestamp: 1560776446
Build timestamp as int: 1560776446
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
0.32.2
  </code>
</pre>

**Anything else relevant?**

Thanks for your help!

**Comment by dv29** [comment]
I can replicate this, found the root cause to be in rules_typescript.
Trying to figure out resolutions but I dont understand how to make it work for development.
How to integrate local rules_typescrip in rules_nodejs when developing locally?

**Comment by dv29** [comment]
Is it documented how to use local `rules_typescript`/`@bazel/typescript` with local `rules_nodejs`?

**Comment by dv29** [comment]
Digging deeper I found that the tsconfig thats generated does not have the src's that are included.

**Comment by alexeagle** [comment]
Had the same problem in https://github.com/angular/tsickle/pull/1042 just now

The issue was the tsconfig.json file had pointers to files outside the compilation (in the `includes` section) so typescript tried to read them. It found the files on the disk, but then our compiler host restricts reads that aren't declared as inputs to make sure the build stays hermetic.

A good answer is to use `build --worker_sandboxing` in the `.bazelrc` as I did in that tsickle PR

**Comment by Dig-Doug** [comment]
Thanks for the tip, seems to have fixed it. For my case it might have been [path references](https://github.com/Dig-Doug/ts-protoc-gen/tree/rules-node-update#ide-code-completion) to generated files.

**Comment by parisholley** [comment]
i'm hitting this issue as well on 2.0.3

BUILD
```
ts_library(
    srcs = glob(["src/submodule/**/*.ts"])
)
```

ts-config.json

```
{
  "include": [
    "src/**/*.ts"
  ],
}
```

only way the error goes away is if restrict the tsconfig to the same include path definition as my glob, which isn't ideal as i'm trying to run multiple ts_librarys in the same BUILD file

**Comment by alexeagle** [comment]
As mentioned above, worker sandboxing is the shortest workaround.
Does ts_project do what you want? Getting changes into ts_library is currently hard

**Comment by ian-h-chamberlain** [comment]
After upgrading to 2.0.3 I ran into a similar issue (we already had `--worker_sandboxing` in `.bazelrc` after running into this previously):
```
ERROR: web/server/lib/BUILD.bazel:30:11: Compiling TypeScript (devmode) //web/server/lib:lib failed (Exit 1): tsc_wrapped.sh failed: error executing command 
  (cd /Users/ichamberlain/Documents/workspace/bazel_out/execroot/com_128technology_i95 && \
  exec env - \
    LC_ALL=en_US.UTF-8 \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/darwin-fastbuild/bin/external/npm_server/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/darwin-fastbuild/bin/web/server/lib/lib_es5_tsconfig.json)
Execution platform: @local_config_platform//:host
error TS5058: The specified path does not exist: '/Users/ichamberlain/Documents/workspace/bazel_out/bazel-workers/worker-0-TypeScriptCompile/com_128technology_i95/web/server/tsconfig.json'.

ERROR: /Users/ichamberlain/Documents/workspace/web/bazel/bin/BUILD.bazel:21:14 Compiling TypeScript (devmode) //web/server/lib:lib failed (Exit 1): tsc_wrapped.sh failed: error executing command 
  (cd /Users/ichamberlain/Documents/workspace/bazel_out/execroot/com_128technology_i95 && \
  exec env - \
    LC_ALL=en_US.UTF-8 \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/darwin-fastbuild/bin/external/npm_server/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/darwin-fastbuild/bin/web/server/lib/lib_es5_tsconfig.json)
```
In this case, the missing `tsconfig.json` was being referenced (via `"extends"`) by the `tsconfig` being passed into the `ts_library` rule. A strange side effect was that manually running the `(cd $execroot && exec env - ... )` command shown by `--sandbox_debug` was successful.

I am able to get past it by using `--strategy TypeScriptCompile=local`, although now I am running into other compile issues (so far seem unrelated).

Thought I would share this in case others run into the same issue. I will probably be investigating using `ts_project` though as it seems to match our use case (and AFAIK did not exist in the previous version of `rules_typescript` that my org was using).
